services:
  db:
    image: postgres:16.4
    container_name: db
    env_file: .env
    volumes:
      - db-store:/var/lib/pgsql/data
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 5s
      interval: 5s
      retries: 10
    environment:
      TZ: UTC
  db-side:
    image: alpine:3.20
    container_name: db-side
    command: ["sh", "-c", "echo 'Wake up db-side'"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-store:
