// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//+build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/halcyon-org/kizuna/internal/adapter/api"
	"github.com/halcyon-org/kizuna/internal/adapter/controller"
	"github.com/halcyon-org/kizuna/internal/adapter/interceptor"
	"github.com/halcyon-org/kizuna/internal/adapter/repository/config"
	ent2 "github.com/halcyon-org/kizuna/internal/adapter/repository/ent"
	"github.com/halcyon-org/kizuna/internal/infrastructure/ent"
	"github.com/halcyon-org/kizuna/internal/usecase"
)

// Injectors from wire.go:

func InitializeControllerSet() (*ControllersSet, error) {
	configRepository, err := config.NewConfigRepository()
	if err != nil {
		return nil, err
	}
	client, err := ent.InitDB(configRepository)
	if err != nil {
		return nil, err
	}
	clientInformationRepository := ent2.NewClientInformationRepository(client)
	clientInformationUsecase := usecase.NewClientInformationUsecase(clientInformationRepository)
	adminServiceHandler := api.NewAdminServiceHandler(clientInformationUsecase)
	providerServiceHandler := api.NewProviderServiceHandler()
	invalid type := api.NewExtInfoServiceHandler()
	koyoServiceHandler := api.NewKoyoServiceHandler()
	serverServiceHandler := api.NewServerServiceHandler()
	adminUserRepository := ent2.NewAdminUserRepository(client)
	koyoInformationRepository := ent2.NewKoyoInformationRepository(client)
	externalInformationRepository := ent2.NewExternalInformationRepository(client)
	authUsecase := usecase.NewAuthUsecase(adminUserRepository, clientInformationRepository, koyoInformationRepository, externalInformationRepository)
	authInterceptorAdapter := interceptor.NewAuthInterceptorAdapter(authUsecase)
	beLifelineController := controller.NewBeLifelineController(adminServiceHandler, providerServiceHandler, invalid type, koyoServiceHandler, serverServiceHandler, authInterceptorAdapter, configRepository)
	controllersSet := &ControllersSet{
		BeLifelineController: beLifelineController,
	}
	return controllersSet, nil
}

// wire.go:

// Adapter
var repositorySet = wire.NewSet(config.NewConfigRepository, ent2.NewAdminUserRepository, ent2.NewClientInformationRepository, ent2.NewKoyoInformationRepository, ent2.NewExternalInformationRepository,
)

var adapterSet = wire.NewSet(api.NewAdminServiceHandler, api.NewProviderServiceHandler, api.NewExtInfoServiceHandler, api.NewKoyoServiceHandler, api.NewServerServiceHandler, interceptor.NewAuthInterceptorAdapter,
)

var controllerSet = wire.NewSet(controller.NewBeLifelineController,
)

// Infrastructure
var infrastructureSet = wire.NewSet(ent.InitDB,
)

// Usecase
var usecaseSet = wire.NewSet(usecase.NewAuthUsecase, usecase.NewKoyoInformationUsecase, usecase.NewClientInformationUsecase,
)

type ControllersSet struct {
	BeLifelineController controller.BeLifelineController
}

