// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/halcyon-org/kizuna/ent/clientdata"
	"github.com/halcyon-org/kizuna/ent/schema/pulid"
)

// ClientData is the model entity for the ClientData schema.
type ClientData struct {
	config `json:"-"`
	// ID of the ent.
	ID pulid.ID `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// APIKey holds the value of the "api_key" field.
	APIKey string `json:"api_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt time.Time `json:"last_used_at,omitempty"`
	// LastUpdatedAt holds the value of the "last_updated_at" field.
	LastUpdatedAt time.Time `json:"last_updated_at,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClientData) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clientdata.FieldID:
			values[i] = new(pulid.ID)
		case clientdata.FieldUsername, clientdata.FieldAPIKey:
			values[i] = new(sql.NullString)
		case clientdata.FieldCreatedAt, clientdata.FieldLastUsedAt, clientdata.FieldLastUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClientData fields.
func (cd *ClientData) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clientdata.FieldID:
			if value, ok := values[i].(*pulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cd.ID = *value
			}
		case clientdata.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				cd.Username = value.String
			}
		case clientdata.FieldAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_key", values[i])
			} else if value.Valid {
				cd.APIKey = value.String
			}
		case clientdata.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cd.CreatedAt = value.Time
			}
		case clientdata.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				cd.LastUsedAt = value.Time
			}
		case clientdata.FieldLastUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_updated_at", values[i])
			} else if value.Valid {
				cd.LastUpdatedAt = value.Time
			}
		default:
			cd.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClientData.
// This includes values selected through modifiers, order, etc.
func (cd *ClientData) Value(name string) (ent.Value, error) {
	return cd.selectValues.Get(name)
}

// Update returns a builder for updating this ClientData.
// Note that you need to call ClientData.Unwrap() before calling this method if this ClientData
// was returned from a transaction, and the transaction was committed or rolled back.
func (cd *ClientData) Update() *ClientDataUpdateOne {
	return NewClientDataClient(cd.config).UpdateOne(cd)
}

// Unwrap unwraps the ClientData entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cd *ClientData) Unwrap() *ClientData {
	_tx, ok := cd.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClientData is not a transactional entity")
	}
	cd.config.driver = _tx.drv
	return cd
}

// String implements the fmt.Stringer.
func (cd *ClientData) String() string {
	var builder strings.Builder
	builder.WriteString("ClientData(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cd.ID))
	builder.WriteString("username=")
	builder.WriteString(cd.Username)
	builder.WriteString(", ")
	builder.WriteString("api_key=")
	builder.WriteString(cd.APIKey)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(cd.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_used_at=")
	builder.WriteString(cd.LastUsedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_updated_at=")
	builder.WriteString(cd.LastUpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ClientDataSlice is a parsable slice of ClientData.
type ClientDataSlice []*ClientData
