// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/halcyon-org/kizuna/ent/clientdata"
	"github.com/halcyon-org/kizuna/ent/predicate"
)

// ClientDataDelete is the builder for deleting a ClientData entity.
type ClientDataDelete struct {
	config
	hooks    []Hook
	mutation *ClientDataMutation
}

// Where appends a list predicates to the ClientDataDelete builder.
func (cdd *ClientDataDelete) Where(ps ...predicate.ClientData) *ClientDataDelete {
	cdd.mutation.Where(ps...)
	return cdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cdd *ClientDataDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, cdd.sqlExec, cdd.mutation, cdd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (cdd *ClientDataDelete) ExecX(ctx context.Context) int {
	n, err := cdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cdd *ClientDataDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clientdata.Table, sqlgraph.NewFieldSpec(clientdata.FieldID, field.TypeString))
	if ps := cdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	cdd.mutation.done = true
	return affected, err
}

// ClientDataDeleteOne is the builder for deleting a single ClientData entity.
type ClientDataDeleteOne struct {
	cdd *ClientDataDelete
}

// Where appends a list predicates to the ClientDataDelete builder.
func (cddo *ClientDataDeleteOne) Where(ps ...predicate.ClientData) *ClientDataDeleteOne {
	cddo.cdd.mutation.Where(ps...)
	return cddo
}

// Exec executes the deletion query.
func (cddo *ClientDataDeleteOne) Exec(ctx context.Context) error {
	n, err := cddo.cdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clientdata.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cddo *ClientDataDeleteOne) ExecX(ctx context.Context) {
	if err := cddo.Exec(ctx); err != nil {
		panic(err)
	}
}
