// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/halcyon-org/kizuna/ent/clientdata"
	"github.com/halcyon-org/kizuna/ent/schema/pulid"
)

// ClientDataCreate is the builder for creating a ClientData entity.
type ClientDataCreate struct {
	config
	mutation *ClientDataMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (cdc *ClientDataCreate) SetUsername(s string) *ClientDataCreate {
	cdc.mutation.SetUsername(s)
	return cdc
}

// SetAPIKey sets the "api_key" field.
func (cdc *ClientDataCreate) SetAPIKey(s string) *ClientDataCreate {
	cdc.mutation.SetAPIKey(s)
	return cdc
}

// SetCreatedAt sets the "created_at" field.
func (cdc *ClientDataCreate) SetCreatedAt(t time.Time) *ClientDataCreate {
	cdc.mutation.SetCreatedAt(t)
	return cdc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cdc *ClientDataCreate) SetNillableCreatedAt(t *time.Time) *ClientDataCreate {
	if t != nil {
		cdc.SetCreatedAt(*t)
	}
	return cdc
}

// SetLastUsedAt sets the "last_used_at" field.
func (cdc *ClientDataCreate) SetLastUsedAt(t time.Time) *ClientDataCreate {
	cdc.mutation.SetLastUsedAt(t)
	return cdc
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (cdc *ClientDataCreate) SetNillableLastUsedAt(t *time.Time) *ClientDataCreate {
	if t != nil {
		cdc.SetLastUsedAt(*t)
	}
	return cdc
}

// SetLastUpdatedAt sets the "last_updated_at" field.
func (cdc *ClientDataCreate) SetLastUpdatedAt(t time.Time) *ClientDataCreate {
	cdc.mutation.SetLastUpdatedAt(t)
	return cdc
}

// SetNillableLastUpdatedAt sets the "last_updated_at" field if the given value is not nil.
func (cdc *ClientDataCreate) SetNillableLastUpdatedAt(t *time.Time) *ClientDataCreate {
	if t != nil {
		cdc.SetLastUpdatedAt(*t)
	}
	return cdc
}

// SetID sets the "id" field.
func (cdc *ClientDataCreate) SetID(pu pulid.ID) *ClientDataCreate {
	cdc.mutation.SetID(pu)
	return cdc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cdc *ClientDataCreate) SetNillableID(pu *pulid.ID) *ClientDataCreate {
	if pu != nil {
		cdc.SetID(*pu)
	}
	return cdc
}

// Mutation returns the ClientDataMutation object of the builder.
func (cdc *ClientDataCreate) Mutation() *ClientDataMutation {
	return cdc.mutation
}

// Save creates the ClientData in the database.
func (cdc *ClientDataCreate) Save(ctx context.Context) (*ClientData, error) {
	cdc.defaults()
	return withHooks(ctx, cdc.sqlSave, cdc.mutation, cdc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cdc *ClientDataCreate) SaveX(ctx context.Context) *ClientData {
	v, err := cdc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cdc *ClientDataCreate) Exec(ctx context.Context) error {
	_, err := cdc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cdc *ClientDataCreate) ExecX(ctx context.Context) {
	if err := cdc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cdc *ClientDataCreate) defaults() {
	if _, ok := cdc.mutation.CreatedAt(); !ok {
		v := clientdata.DefaultCreatedAt()
		cdc.mutation.SetCreatedAt(v)
	}
	if _, ok := cdc.mutation.LastUsedAt(); !ok {
		v := clientdata.DefaultLastUsedAt()
		cdc.mutation.SetLastUsedAt(v)
	}
	if _, ok := cdc.mutation.LastUpdatedAt(); !ok {
		v := clientdata.DefaultLastUpdatedAt()
		cdc.mutation.SetLastUpdatedAt(v)
	}
	if _, ok := cdc.mutation.ID(); !ok {
		v := clientdata.DefaultID()
		cdc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cdc *ClientDataCreate) check() error {
	if _, ok := cdc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "ClientData.username"`)}
	}
	if v, ok := cdc.mutation.Username(); ok {
		if err := clientdata.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ClientData.username": %w`, err)}
		}
	}
	if _, ok := cdc.mutation.APIKey(); !ok {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required field "ClientData.api_key"`)}
	}
	if _, ok := cdc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ClientData.created_at"`)}
	}
	if _, ok := cdc.mutation.LastUsedAt(); !ok {
		return &ValidationError{Name: "last_used_at", err: errors.New(`ent: missing required field "ClientData.last_used_at"`)}
	}
	if _, ok := cdc.mutation.LastUpdatedAt(); !ok {
		return &ValidationError{Name: "last_updated_at", err: errors.New(`ent: missing required field "ClientData.last_updated_at"`)}
	}
	return nil
}

func (cdc *ClientDataCreate) sqlSave(ctx context.Context) (*ClientData, error) {
	if err := cdc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cdc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cdc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*pulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cdc.mutation.id = &_node.ID
	cdc.mutation.done = true
	return _node, nil
}

func (cdc *ClientDataCreate) createSpec() (*ClientData, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientData{config: cdc.config}
		_spec = sqlgraph.NewCreateSpec(clientdata.Table, sqlgraph.NewFieldSpec(clientdata.FieldID, field.TypeString))
	)
	if id, ok := cdc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cdc.mutation.Username(); ok {
		_spec.SetField(clientdata.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := cdc.mutation.APIKey(); ok {
		_spec.SetField(clientdata.FieldAPIKey, field.TypeString, value)
		_node.APIKey = value
	}
	if value, ok := cdc.mutation.CreatedAt(); ok {
		_spec.SetField(clientdata.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cdc.mutation.LastUsedAt(); ok {
		_spec.SetField(clientdata.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = value
	}
	if value, ok := cdc.mutation.LastUpdatedAt(); ok {
		_spec.SetField(clientdata.FieldLastUpdatedAt, field.TypeTime, value)
		_node.LastUpdatedAt = value
	}
	return _node, _spec
}

// ClientDataCreateBulk is the builder for creating many ClientData entities in bulk.
type ClientDataCreateBulk struct {
	config
	err      error
	builders []*ClientDataCreate
}

// Save creates the ClientData entities in the database.
func (cdcb *ClientDataCreateBulk) Save(ctx context.Context) ([]*ClientData, error) {
	if cdcb.err != nil {
		return nil, cdcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cdcb.builders))
	nodes := make([]*ClientData, len(cdcb.builders))
	mutators := make([]Mutator, len(cdcb.builders))
	for i := range cdcb.builders {
		func(i int, root context.Context) {
			builder := cdcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cdcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cdcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cdcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cdcb *ClientDataCreateBulk) SaveX(ctx context.Context) []*ClientData {
	v, err := cdcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cdcb *ClientDataCreateBulk) Exec(ctx context.Context) error {
	_, err := cdcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cdcb *ClientDataCreateBulk) ExecX(ctx context.Context) {
	if err := cdcb.Exec(ctx); err != nil {
		panic(err)
	}
}
