// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/halcyon-org/kizuna/ent/externalinformation"
	"github.com/halcyon-org/kizuna/ent/predicate"
	"github.com/halcyon-org/kizuna/ent/schema/pulid"
)

// ExternalInformationQuery is the builder for querying ExternalInformation entities.
type ExternalInformationQuery struct {
	config
	ctx        *QueryContext
	order      []externalinformation.OrderOption
	inters     []Interceptor
	predicates []predicate.ExternalInformation
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExternalInformationQuery builder.
func (eiq *ExternalInformationQuery) Where(ps ...predicate.ExternalInformation) *ExternalInformationQuery {
	eiq.predicates = append(eiq.predicates, ps...)
	return eiq
}

// Limit the number of records to be returned by this query.
func (eiq *ExternalInformationQuery) Limit(limit int) *ExternalInformationQuery {
	eiq.ctx.Limit = &limit
	return eiq
}

// Offset to start from.
func (eiq *ExternalInformationQuery) Offset(offset int) *ExternalInformationQuery {
	eiq.ctx.Offset = &offset
	return eiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eiq *ExternalInformationQuery) Unique(unique bool) *ExternalInformationQuery {
	eiq.ctx.Unique = &unique
	return eiq
}

// Order specifies how the records should be ordered.
func (eiq *ExternalInformationQuery) Order(o ...externalinformation.OrderOption) *ExternalInformationQuery {
	eiq.order = append(eiq.order, o...)
	return eiq
}

// First returns the first ExternalInformation entity from the query.
// Returns a *NotFoundError when no ExternalInformation was found.
func (eiq *ExternalInformationQuery) First(ctx context.Context) (*ExternalInformation, error) {
	nodes, err := eiq.Limit(1).All(setContextOp(ctx, eiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{externalinformation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eiq *ExternalInformationQuery) FirstX(ctx context.Context) *ExternalInformation {
	node, err := eiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExternalInformation ID from the query.
// Returns a *NotFoundError when no ExternalInformation ID was found.
func (eiq *ExternalInformationQuery) FirstID(ctx context.Context) (id pulid.ID, err error) {
	var ids []pulid.ID
	if ids, err = eiq.Limit(1).IDs(setContextOp(ctx, eiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{externalinformation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eiq *ExternalInformationQuery) FirstIDX(ctx context.Context) pulid.ID {
	id, err := eiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExternalInformation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExternalInformation entity is found.
// Returns a *NotFoundError when no ExternalInformation entities are found.
func (eiq *ExternalInformationQuery) Only(ctx context.Context) (*ExternalInformation, error) {
	nodes, err := eiq.Limit(2).All(setContextOp(ctx, eiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{externalinformation.Label}
	default:
		return nil, &NotSingularError{externalinformation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eiq *ExternalInformationQuery) OnlyX(ctx context.Context) *ExternalInformation {
	node, err := eiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExternalInformation ID in the query.
// Returns a *NotSingularError when more than one ExternalInformation ID is found.
// Returns a *NotFoundError when no entities are found.
func (eiq *ExternalInformationQuery) OnlyID(ctx context.Context) (id pulid.ID, err error) {
	var ids []pulid.ID
	if ids, err = eiq.Limit(2).IDs(setContextOp(ctx, eiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{externalinformation.Label}
	default:
		err = &NotSingularError{externalinformation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eiq *ExternalInformationQuery) OnlyIDX(ctx context.Context) pulid.ID {
	id, err := eiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExternalInformations.
func (eiq *ExternalInformationQuery) All(ctx context.Context) ([]*ExternalInformation, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryAll)
	if err := eiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExternalInformation, *ExternalInformationQuery]()
	return withInterceptors[[]*ExternalInformation](ctx, eiq, qr, eiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eiq *ExternalInformationQuery) AllX(ctx context.Context) []*ExternalInformation {
	nodes, err := eiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExternalInformation IDs.
func (eiq *ExternalInformationQuery) IDs(ctx context.Context) (ids []pulid.ID, err error) {
	if eiq.ctx.Unique == nil && eiq.path != nil {
		eiq.Unique(true)
	}
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryIDs)
	if err = eiq.Select(externalinformation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eiq *ExternalInformationQuery) IDsX(ctx context.Context) []pulid.ID {
	ids, err := eiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eiq *ExternalInformationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryCount)
	if err := eiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eiq, querierCount[*ExternalInformationQuery](), eiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eiq *ExternalInformationQuery) CountX(ctx context.Context) int {
	count, err := eiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eiq *ExternalInformationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eiq.ctx, ent.OpQueryExist)
	switch _, err := eiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eiq *ExternalInformationQuery) ExistX(ctx context.Context) bool {
	exist, err := eiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExternalInformationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eiq *ExternalInformationQuery) Clone() *ExternalInformationQuery {
	if eiq == nil {
		return nil
	}
	return &ExternalInformationQuery{
		config:     eiq.config,
		ctx:        eiq.ctx.Clone(),
		order:      append([]externalinformation.OrderOption{}, eiq.order...),
		inters:     append([]Interceptor{}, eiq.inters...),
		predicates: append([]predicate.ExternalInformation{}, eiq.predicates...),
		// clone intermediate query.
		sql:  eiq.sql.Clone(),
		path: eiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExternalInformation.Query().
//		GroupBy(externalinformation.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eiq *ExternalInformationQuery) GroupBy(field string, fields ...string) *ExternalInformationGroupBy {
	eiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExternalInformationGroupBy{build: eiq}
	grbuild.flds = &eiq.ctx.Fields
	grbuild.label = externalinformation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ExternalInformation.Query().
//		Select(externalinformation.FieldName).
//		Scan(ctx, &v)
func (eiq *ExternalInformationQuery) Select(fields ...string) *ExternalInformationSelect {
	eiq.ctx.Fields = append(eiq.ctx.Fields, fields...)
	sbuild := &ExternalInformationSelect{ExternalInformationQuery: eiq}
	sbuild.label = externalinformation.Label
	sbuild.flds, sbuild.scan = &eiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExternalInformationSelect configured with the given aggregations.
func (eiq *ExternalInformationQuery) Aggregate(fns ...AggregateFunc) *ExternalInformationSelect {
	return eiq.Select().Aggregate(fns...)
}

func (eiq *ExternalInformationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eiq); err != nil {
				return err
			}
		}
	}
	for _, f := range eiq.ctx.Fields {
		if !externalinformation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eiq.path != nil {
		prev, err := eiq.path(ctx)
		if err != nil {
			return err
		}
		eiq.sql = prev
	}
	return nil
}

func (eiq *ExternalInformationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExternalInformation, error) {
	var (
		nodes   = []*ExternalInformation{}
		withFKs = eiq.withFKs
		_spec   = eiq.querySpec()
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, externalinformation.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExternalInformation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExternalInformation{config: eiq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (eiq *ExternalInformationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eiq.querySpec()
	_spec.Node.Columns = eiq.ctx.Fields
	if len(eiq.ctx.Fields) > 0 {
		_spec.Unique = eiq.ctx.Unique != nil && *eiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eiq.driver, _spec)
}

func (eiq *ExternalInformationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(externalinformation.Table, externalinformation.Columns, sqlgraph.NewFieldSpec(externalinformation.FieldID, field.TypeString))
	_spec.From = eiq.sql
	if unique := eiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eiq.path != nil {
		_spec.Unique = true
	}
	if fields := eiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, externalinformation.FieldID)
		for i := range fields {
			if fields[i] != externalinformation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eiq *ExternalInformationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eiq.driver.Dialect())
	t1 := builder.Table(externalinformation.Table)
	columns := eiq.ctx.Fields
	if len(columns) == 0 {
		columns = externalinformation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eiq.sql != nil {
		selector = eiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eiq.ctx.Unique != nil && *eiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eiq.predicates {
		p(selector)
	}
	for _, p := range eiq.order {
		p(selector)
	}
	if offset := eiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExternalInformationGroupBy is the group-by builder for ExternalInformation entities.
type ExternalInformationGroupBy struct {
	selector
	build *ExternalInformationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eigb *ExternalInformationGroupBy) Aggregate(fns ...AggregateFunc) *ExternalInformationGroupBy {
	eigb.fns = append(eigb.fns, fns...)
	return eigb
}

// Scan applies the selector query and scans the result into the given value.
func (eigb *ExternalInformationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eigb.build.ctx, ent.OpQueryGroupBy)
	if err := eigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExternalInformationQuery, *ExternalInformationGroupBy](ctx, eigb.build, eigb, eigb.build.inters, v)
}

func (eigb *ExternalInformationGroupBy) sqlScan(ctx context.Context, root *ExternalInformationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eigb.fns))
	for _, fn := range eigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eigb.flds)+len(eigb.fns))
		for _, f := range *eigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExternalInformationSelect is the builder for selecting fields of ExternalInformation entities.
type ExternalInformationSelect struct {
	*ExternalInformationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eis *ExternalInformationSelect) Aggregate(fns ...AggregateFunc) *ExternalInformationSelect {
	eis.fns = append(eis.fns, fns...)
	return eis
}

// Scan applies the selector query and scans the result into the given value.
func (eis *ExternalInformationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eis.ctx, ent.OpQuerySelect)
	if err := eis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExternalInformationQuery, *ExternalInformationSelect](ctx, eis.ExternalInformationQuery, eis, eis.inters, v)
}

func (eis *ExternalInformationSelect) sqlScan(ctx context.Context, root *ExternalInformationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eis.fns))
	for _, fn := range eis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
