name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: |
          echo "datetime=$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.6
        with:
          token_format: access_token
          workload_identity_provider: "projects/494673853308/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-actions"
          service_account: github-actions@vaulted-zodiac-431004-s7.iam.gserviceaccount.com
      - name: Login to GCR
        uses: docker/login-action@v3.3.0
        with:
          registry: asia.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/kizuna/Dockerfile
          tags: |
            asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:latest
            asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:${{ steps.vars.outputs.sha_short }}
            asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:${{ steps.vars.outputs.datetime }}
