name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    environment: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2.1.7
        with:
          token_format: access_token
          workload_identity_provider: "projects/494673853308/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-actions"
          service_account: github-actions@vaulted-zodiac-431004-s7.iam.gserviceaccount.com
      - name: Login to GCR
        uses: docker/login-action@v3.3.0
        with:
          registry: asia.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/kizuna/Dockerfile
          tags: |
            asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:latest
            asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:${{ needs.release-please.outputs.tag-name }}
            asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:${{ steps.vars.outputs.sha_short }}
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2.7.2
        with:
          service: kizuna
          image: asia.gcr.io/vaulted-zodiac-431004-s7/kizuna:${{ needs.release-please.outputs.tag-name }}
