// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ExternalInformation is the predicate function for externalinformation builders.
type ExternalInformation func(*sql.Selector)

// KoyoData is the predicate function for koyodata builders.
type KoyoData func(*sql.Selector)

// KoyoInformation is the predicate function for koyoinformation builders.
type KoyoInformation func(*sql.Selector)
